version: '3' # version には Docker Compose というツールのバージョンを記述します。ここでは 3 というバージョンを指定しています。
services:    # services の 1 つ下の階層には、全体を構成する要素（「サービス」といいます）を記述します。
  app:        # app はサービスの名前です。サービスはコンテナに対応するので、コンテナの名前に対応すると思って問題ありません。名前の付け方は本来自由ですが、ここでは「アプリケーション」を意味する app としておきましょう。
    build: .  # build は指定したディレクトリにある Dockerfile から Docker イメージを構築するための記述です。ここでは同じ階層のディレクトリを意味する . を指定し、同じディレクトリにある Dockerfile（つまり、先ほど作成した Dockerfile）を使用するように記述しています。
    tty: true # tty は、コンテナを起動させ続けるための記述です。
    volumes:  # volumes は、「マウント」と呼ばれるファイル共有の設定です。ここでは、ホスト OS（Windows や macOS）の .（同じ階層のディレクトリ）と、コンテナの /linux-study というディレクトリを紐づけています。
      - .:/linux-study